# Site settings
title: Matteo Piombo
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Personal Web Site About Me
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blogger.fedro.org" # the base hostname & protocol for your site
twitter_username: perlfly
github_username:  perlfly

# Build settings
markdown: kramdown
